version: "3.9"
services:
  brains:
    image: registry.scribblej.com/trolbrains:latest
    build: ./brains
    ports:
      - target: 8081
        published: 8081
    configs:
      - source: brainconfig
        target: /usr/src/app/trolbrains.conf
      - source: cameraconfig
        target: /cameras-config.json
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
    volumes:
      - type: bind
        source: /mnt/superdrbd1/docker/trolbrains
        target: /mnt/brains
      - type: volume
        source: nas2-kavids
        target: /mnt/outgoing
    user: 120:120

  jsclient:
    image: registry.scribblej.com/troljsclient:latest
    build: ./jsclient
    ports: 
      - target: 80
        published: 8000
    configs:
      - source: jsclientconfig
        target: /usr/share/nginx/html/config.js
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s

  bot:
    image: registry.scribblej.com/trolbot:latest
    build: ./bot
    configs:
      - source: botconfig
        target: /usr/src/app/discord.conf
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
  kafilemover:
    image: registry.scribblej.com/kafilemover:latest
    build: .
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
    volumes:
      - type: volume
        source: xsplit-video1
        target: /mnt/incoming
      - type: volume
        source: nas2-kavids
        target: /mnt/outgoing
    user: 120:120

volumes:
  xsplit-video1:
    driver_opts:
      type: "cifs"
      device: "//TESLA/Users/Kitten Academy/Videos/Xsplit/Broadcaster/scribblecj@gmail.com"
      o: "addr=TESLA,username=${xsplit_user},password=${xsplit_pass},uid=120,gid=120,vers=2.0"
  nas2-kavids:
    driver_opts:
      type: "cifs"
      device: "//nas2/home/xsplit-rec"
      o: "vers=2.0,addr=nas2,username=${nas2_user},password=${nas2_pass},uid=120,gid=120"

configs:
  jsclientconfig:
    file: ./configs/jsclient-config.js
  botconfig:
    file: ./configs/bot-config.conf
  brainconfig:
    file: ./configs/brains-config.json
  cameraconfig:
    file: ./configs/cameras-config.json

